//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Managment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string dob { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public string department { get; set; }
        public string salary { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string updated_by { get; set; }
    
        public virtual empDetail empDetails1 { get; set; }
        public virtual empDetail empDetail1 { get; set; }
    }
}
